### ISSUE TITLE
Change bot name of myuwubot to ouruwubot

### ISSUE THREAD

**Issue by J-Arun-Mani** [aicantar/uwubot#1]
In spirit of interesting open source and to encourage community contribution, I think, the bot name can be changed to `ouruwubot`. What y'all think ?

**Comment by aicantar** [comment]
Telegram unfortunately doesn't allow to change the bot name except creating a new one.

Besides, there are deployment instructions that allow anybody to create their own bot using any possessive pronoun in the name provided that it's not taken already. :p
